FROM python:3.9-slim

#set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

#set working dir
WORKDIR /app

#install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

#copy local code to container
COPY . .

#expose port 5000 to allow communication to/from flask server
EXPOSE 5000

#run app
CMD ["flask", "run", "--host=0.0.0.0"]